/**
 * This class is generated by jOOQ
 */
package com.lowang.ormjooq.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

	private static final long serialVersionUID = -101391557;

	private Long    id;
	private String  address;
	private Boolean locked;
	private String  mobile;
	private String  name;

	public User() {}

	public User(User value) {
		this.id = value.id;
		this.address = value.address;
		this.locked = value.locked;
		this.mobile = value.mobile;
		this.name = value.name;
	}

	public User(
		Long    id,
		String  address,
		Boolean locked,
		String  mobile,
		String  name
	) {
		this.id = id;
		this.address = address;
		this.locked = locked;
		this.mobile = mobile;
		this.name = name;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("User (");

		sb.append(id);
		sb.append(", ").append(address);
		sb.append(", ").append(locked);
		sb.append(", ").append(mobile);
		sb.append(", ").append(name);

		sb.append(")");
		return sb.toString();
	}
}
