/**
 * This class is generated by jOOQ
 */
package com.lowang.ormjooq.domain;


import com.lowang.ormjooq.domain.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in lowang
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table lowang.user
	 */
	public static final User USER = com.lowang.ormjooq.domain.tables.User.USER;
}
