/**
 * This class is generated by jOOQ
 */
package com.lowang.ormjooq.domain.tables.records;


import com.lowang.ormjooq.domain.tables.User;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record5<Long, String, Boolean, String, String> {

	private static final long serialVersionUID = -632262665;

	/**
	 * Setter for <code>lowang.user.id</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lowang.user.id</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>lowang.user.address</code>.
	 */
	public void setAddress(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lowang.user.address</code>.
	 */
	public String getAddress() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>lowang.user.locked</code>.
	 */
	public void setLocked(Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lowang.user.locked</code>.
	 */
	public Boolean getLocked() {
		return (Boolean) getValue(2);
	}

	/**
	 * Setter for <code>lowang.user.mobile</code>.
	 */
	public void setMobile(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>lowang.user.mobile</code>.
	 */
	public String getMobile() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>lowang.user.name</code>.
	 */
	public void setName(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>lowang.user.name</code>.
	 */
	public String getName() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, Boolean, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, Boolean, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return User.USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return User.USER.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field3() {
		return User.USER.LOCKED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return User.USER.MOBILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return User.USER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value3() {
		return getLocked();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMobile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(Boolean value) {
		setLocked(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(String value) {
		setMobile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(Long value1, String value2, Boolean value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(Long id, String address, Boolean locked, String mobile, String name) {
		super(User.USER);

		setValue(0, id);
		setValue(1, address);
		setValue(2, locked);
		setValue(3, mobile);
		setValue(4, name);
	}

  @Override
  public Long component1() {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public String component2() {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public Boolean component3() {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public String component4() {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public String component5() {
    // TODO Auto-generated method stub
    return null;
  }
}
